### ISSUE TITLE
impact of interface{}?

### ISSUE THREAD

**Issue by steviesama** [ReactiveX/RxGo#38]
I have limited experience with it, but I've often read that there is a cost associated with the use of the empty interface in the boxing and unboxing. If you use reactivex in the data access layer and basically all your data is filtered by it, or at least the filtered/indexed fields, is there  a noticeable impact to be observed by it's use? I usually just use the explicit data types, but I recognize where `interface{}` is useful. I used it to generate json in my `JsonBuilder` package as it would have been basically impossible otherwise.

**Comment by jochasinga** [comment]
@steviesama what comes obviously with casting down the type and up using type assertion is boilerplate (which isn't something totally new in Go). Some say you risk compile-time type safety, and panics are bound to happen if you're not careful when doing type assertion.

Normally, what you would do to make it completely safe is thorough type switching, like this:

```go

switch v := v.(type) {
case int:
case float64:
case string:
// ...
}

```

But since Go does not enforce thorough matching or even a default case, you'll have to do this manually.

**Comment by steviesama** [comment]
@jochasinga Thanks. I figured short of number crunching that the performance loss was likely negligible. Thanks for the response.
