### ISSUE TITLE
Strange behaviour with two and more pipes

### ISSUE THREAD

**Issue by ArkadyB** [ReactiveX/RxGo#46]
Hi, 
I was doing some testing and found package behaves strange with more than one observers connected to source.

A simple app is listening for Stdin and sends all the values into channel which is in turn connected with observers via iterable source. With this scenario app requires me to put values twice to have it processed. Am i doing something wrong?

```go

func main() {

	lines := make(chan interface{})
	go func() {
		defer close(lines)
		scanner := bufio.NewScanner(os.Stdin)
		for scanner.Scan() {
			lines <- scanner.Text()
		}
	}()

	process := observer.Observer{

		// Register a handler function for every next available item.
		NextHandler: func(item interface{}) {
			fmt.Printf("Processing: %v\n", item)			
		},

		// Register a handler for any emitted error.
		ErrHandler: func(err error) {
			fmt.Printf("Encountered error: %v\n", err)
		},

		// Register a handler when a stream is completed.
		DoneHandler: func() {
			fmt.Println("Done!")
		},
	}

	isOne := func(str interface{}) bool {
		return str == "one"
	}

	isTwo := func(str interface{}) bool {
		return str == "two"
	}

	mapOne := func(str interface{}) interface{} {
		return str
	}

	mapTwo := func(str interface{}) interface{} {
		return str
	}

	it, err := iterable.New(lines)
	if err != nil {
		fmt.Printf(err.Error())
	}

	src := observable.From(it)
	pipe1 := src.Filter(isOne).Map(mapOne).Subscribe(process)
	pipe2 := src.Filter(isTwo).Map(mapTwo).Subscribe(process)

	select {
	case <-pipe1:
	case <-pipe2:
	}
}

```

**Comment by jochasinga** [comment]
From the first look, it seems like because the goroutine which scans and chuck the text into `lines` channel doesn't block, by the time the program reaches the line where you create an iterable `lines` is still empty.  

You can probably do the following:

+ Print `len(lines)` just before creating the iterable
+ If this is the case, you will have to block/wait for `lines` to receive something before creating an iterable from it and start processing.

Let me know if that works out.

**Comment by ArkadyB** [comment]
It does not seem to work. If you simply run the app and click Enter several times, it does apply only one filer per enter. So it will be Enter -> isOne, Enter -> isTwo, Enter -> isOne, Enter -> isTwo .... and so one. It does not seem to ever try checking both filters for each new value in the channel.

**Comment by jochasinga** [comment]
@ArkadyB that's because you're using a single source which ![fan out](https://blog.golang.org/pipelines) to two separate goroutines. The data distributes "evenly" to both routines, not copied. If instead of inputting the text manually to `os.Stdin` you create a for loop that sends "one" and "two" alternately to `lines` very quickly you'll see the indeterminate behavior rather than a pattern.

What you are experiencing is the indeterminate asynchronous behavior that seems determinate because the input is send to `lines` slowly. The source channel doesn't know if the data is "one" or "two" and there's no way it can send to the correct goroutine (hence "one" is sent to `pipe2` at times and thus not printed, and vice versa).

To get a predictable behavior, either use a single stream with a more inclusive filter function:

```go

isOneOrTwo := func(i interface{}) bool {
        return i == "one" || i == "two"
}
<-src.Filter(isOneOrTwo).Subscribe(process)

```

or send `scanner.Text()` to two source channels i.e. `lines1` and `lines2`:

```go

lines1 := make(chan interface{})
lines2 := make(chan interface{})

go func() {
        scanner := bufio.NewScanner(os.Stdin)
        for scanner.Scan() {
                lines1 <- scanner.Text()
                lines2 <- scanner.Text()
        }
}()

src1 := observable.Observable(lines1)
src2 := observable.Observable(lines2)

p1 := src1.Filter(isOne).Subscribe(process)
p2 := src2.Filter(isTwo).Subscribe(process)

select {
case <-p1:
case <-p2:
}

```

**Comment by ArkadyB** [comment]
@jochasinga, thanks for the answer!

Would not be correct to send data to all the subscribed sources?

**Comment by jochasinga** [comment]
Sorry I don't understand the question. Basically, a source, may it be a channel, slice, array, or an observable, can only be "streamed" down a single pipeline, or get distributed to more. You can't do something like you would do in a pub-sub pattern where a publisher emits an event, and all subscribers that subscribe to that event gets the message (which might be something you were trying to do?).

So if you start using operators on a single source to create many pipelines, you are distributing the processing task among all of them concurrently.

The closest you can do to make several pipelines processing the same data from a single source is through a `Connectable`:

```go

src := connectable.From(it)
sc := src.Subscribe(process1).Subscribe(process2).Subscribe(process3).Connect()
<-sc

```

When `Connect()` is called, each `Subscribe` creates a new goroutine that use the subscribed process to process the source stream. It returns a `<-chan (chan subscription.Subscription)`.

**Comment by ArkadyB** [comment]
Thank you for help! Yes, i guess i was trying implmenting pub-sub using reactive channels, which is probably not the right mix. Will rethink the solution to map patterns correctly.
