### ISSUE TITLE
Panic handling

### ISSUE THREAD

**Issue by dfilipovic39** [ReactiveX/RxGo#6]
Hi,
first of all, great initiative. Rx is something that should definitely be implemented in Go.
There should be maybe some kind of panic error handling in handlers. For example, basic implementation would be something like:
```
// OnNext applies Observer's NextHandler to an Item
func (ob Observer) OnNext(item interface{}) {
	defer func() {
		if (recover() != nil) {
			ob.OnError(errors.New(7, "Panicked!"))
		}
	}()
	switch item := item.(type) {
	case error:
		return
	default:
		if ob.NextHandler != nil {
			ob.NextHandler(item)
		}
	}
}
```

A better approach would be an optional panic handler, as the deffer is not very performant.

**Comment by jochasinga** [comment]
@tarqe39 great pointing this out and really appreciate the encouragement and contribution. It is the design I've been thinking about.

The current behavior is if one decides to `Subscribe` a `NextFunc` as an `EventHandler` without an `ErrFunc`, an error in the stream will be ignored but will still result in an automatic termination of that stream processing. This way, `OnNext` and `OnError` are completely isolated and the latter should be defined and invoked explicitly. This explicitness was intentionally aligned to Go's pragmatism.

However, the implicit break of the channel looping when an error is found is still not very explicit. So the decision would be:
- Either have an implicit call to `observer.OnError` (or `ErrHandler`) in the `OnNext` when a the item is an error.
- or be explicit about everything and including delegating the termination of channel processing to the user to define behavior in the `observer.ErrHandler`.

Let me know what you think.

**Comment by tarqe39** [comment]
@jochasinga, for start, i think I'd go with implicit termination of stream when either error is in the stream or when panic occurs (if I understood your dilemma right) as this is the default behavior by the ReactiveX documentation. [Catch operator](http://reactivex.io/documentation/operators/catch.html) is used to handle situations where the stream should not be terminated on error.
So the `panic() `should be caught, and cause `OutterLoop` to break same as error currently does. I didn't dig too much in the code so i cant tell for sure. And there should be a way to distinct `error` and error caused by `panic` by the `observer.ErrHandler`.

Does this make any sense? :)

**Comment by jochasinga** [comment]
@tarqe39 I apologize for the misunderstanding. You were talking about panic handling as an addition to handling of an error item in the stream by `observer.ErrHandler`, right?

**Comment by tarqe39** [comment]
That's right. I think that a single point to handle all errors/panics should be of great help and make the library more robust than handling panics for each subscriber individually.

**Comment by influx6** [comment]
I am in agreement with the view of using the `observer.ErrHandler` because since we are dealing with streams, then ensure adequate handling of panic should stay closed to the idiomatic reasoning in Go. Although I would advice to have error object created specifically for a panic. Because when you think about it, if a panic occurs which is not a desired effect in running code then something bad, really bad and crippling occurs and should be immediately dealt with.

I have a long term project that I am working on though in a sense different from `RxGo` but do follow the consistent approach of pure functions, and I adopted this approach. 

I only question that does pop into my mind is simply this:

1. Should the library handle the panic occurance action and behaviour
2. Should the client user giving the responsibility to handle this panic error.

If we think idiomatically in Go, then the best option is 2. 

You want the user to actually behave has desired for that panic or any such error that occurs. 

Else let them provide a `Handler` that has a `Handler.PanicError` type, so has to specifically handle panics.

**Comment by jochasinga** [comment]
At this point I'm making the change to `Subscribe` method such that it's the user's responsibility to handle the on-stream error using `observer.ErrHandler`:

```go

ctx := stream.Subscribe(handlers.ErrFunc(func(err error) {
        // crash the program when error occurs
        log.Fatal(err)
}))
<-ctx.Done()

```

You can also imagine sending the error to a channel to handle it somewhere else or even
create a new Observable with that error emitted on it and subscribe to a new handler/observer.

**Comment by teivah** [comment]
Hey! I'm cleaning the backlog by removing the issues without updates for more than a year. Meanwhile, please check at the v2 to see if the issue is still relevant.
